CREATE INDEX "academic_year_is_active_idx" ON "academic_years" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "achievement_student_idx" ON "achievements" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "achievement_academic_year_idx" ON "achievements" USING btree ("academic_year_id");--> statement-breakpoint
CREATE INDEX "achievement_date_idx" ON "achievements" USING btree ("date");--> statement-breakpoint
CREATE INDEX "activity_log_created_at_idx" ON "activity_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "activity_log_module_idx" ON "activity_logs" USING btree ("module");--> statement-breakpoint
CREATE INDEX "attendance_student_idx" ON "attendances" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "attendance_date_idx" ON "attendances" USING btree ("date");--> statement-breakpoint
CREATE INDEX "attendance_academic_year_idx" ON "attendances" USING btree ("academic_year_id");--> statement-breakpoint
CREATE INDEX "classroom_teacher_idx" ON "classrooms" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "classroom_level_idx" ON "classrooms" USING btree ("level");--> statement-breakpoint
CREATE INDEX "classroom_gender_idx" ON "classrooms" USING btree ("gender");--> statement-breakpoint
CREATE INDEX "dormitory_gender_idx" ON "dormitories" USING btree ("gender");--> statement-breakpoint
CREATE INDEX "memorize_target_category_idx" ON "memorize_targets" USING btree ("category");--> statement-breakpoint
CREATE INDEX "score_student_idx" ON "scores" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "score_subject_idx" ON "scores" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "score_academic_year_idx" ON "scores" USING btree ("academic_year_id");--> statement-breakpoint
CREATE INDEX "student_classroom_student_idx" ON "student_classrooms" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "student_classroom_classroom_idx" ON "student_classrooms" USING btree ("classroom_id");--> statement-breakpoint
CREATE INDEX "student_classroom_academic_year_idx" ON "student_classrooms" USING btree ("academic_year_id");--> statement-breakpoint
CREATE INDEX "student_note_student_idx" ON "student_notes" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "student_note_academic_year_idx" ON "student_notes" USING btree ("academic_year_id");--> statement-breakpoint
CREATE INDEX "student_status_idx" ON "students" USING btree ("status");--> statement-breakpoint
CREATE INDEX "student_dormitory_idx" ON "students" USING btree ("dormitory_id");--> statement-breakpoint
CREATE INDEX "student_gender_idx" ON "students" USING btree ("gender");--> statement-breakpoint
CREATE INDEX "student_name_idx" ON "students" USING btree ("name");--> statement-breakpoint
CREATE INDEX "student_nisn_idx" ON "students" USING btree ("nisn");--> statement-breakpoint
CREATE INDEX "subject_status_idx" ON "subjects" USING btree ("status");--> statement-breakpoint
CREATE INDEX "subject_level_idx" ON "subjects" USING btree ("level");--> statement-breakpoint
CREATE INDEX "system_metric_last_updated_idx" ON "system_metrics" USING btree ("last_updated");--> statement-breakpoint
CREATE INDEX "teacher_attendance_teacher_idx" ON "teacher_attendances" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "teacher_attendance_date_idx" ON "teacher_attendances" USING btree ("date");--> statement-breakpoint
CREATE INDEX "teacher_status_idx" ON "teachers" USING btree ("status");--> statement-breakpoint
CREATE INDEX "teacher_nip_idx" ON "teachers" USING btree ("nip");--> statement-breakpoint
CREATE INDEX "teacher_name_idx" ON "teachers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "teaching_assignment_teacher_idx" ON "teaching_assignments" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "teaching_assignment_subject_idx" ON "teaching_assignments" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "teaching_assignment_classroom_idx" ON "teaching_assignments" USING btree ("classroom_id");--> statement-breakpoint
CREATE INDEX "teaching_assignment_academic_year_idx" ON "teaching_assignments" USING btree ("academic_year_id");--> statement-breakpoint
CREATE INDEX "user_teacher_id_idx" ON "user" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "user_role_idx" ON "user" USING btree ("role");